config/routes.rb
Rails.application.routes.draw do
  root to: "bands#index"

  resources :users do
    get 'toggleboolean'
    collection do
      get 'activate'
    end
  end
  resource :session
  resources :bands do
    resources :albums, only: [:index, :new, :create]
  end

  resources :albums, except: [:index, :new, :create]

  resources :tracks do
    resources :notes
  end

end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :name, :album_id, :track_kind, presence: true
  validates :track_kind, inclusion: {in: ["bonus", "regular track"]}

  belongs_to :album

  has_one :band, through: :album, source: :band

  has_many :notes, class_name: "Note", foreign_key: :track_id, primary_key: :id, :dependent => :destroy

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def index
    @tracks = Track.all

    render :index
  end

  def show

    @track = Track.find(params[:id])
    @notes = @track.notes
    render :show
  end

  def new
    @track = Track.new
    @albums = Album.all
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save!
      flash[:notices] = [" Track Created"]
      redirect_to track_url(@track)
    else
      flash.now[:errors] = ["Track could not be saved."]
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    @albums = Albums.all
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update_attributes(track_params)
      flash[:notices] = [" Track Updated"]
      redirect_to track_url(@track)
    else
      flash.now[:errors] = ["Track could not be updated."]
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])

    @track.destroy!

    redirect_to tracks_url
  end

  private

  def track_params
    params.require(:track).permit(:name, :album_id, :track_kind, :lyrics)
  end

end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<% if action == :new_track %>
  <% send_url = tracks_url%>
  <% submit_button = "Create Track"%>
<%else%>
  <% send_url = track_url%>
  <% submit_button = "Update Track" %>
<% end%>


<form action='<%= send_url %>' method= "POST">
  <%= auth_token_html %>

  <% if action == :update_track%>
    <input type="hidden" value="PATCH" name="_method" >
  <%end%>

  <label for="track_name">Name</label>
  <input type="text" name="track[name]" id="track_name" value="<%=@track.name%>">
  <br>

  <label for="track_album">Track Album</label>
  <!-- dropdown -->
  <select name="track[album_id]" id="track_album" value=<%=@track.album%>>
    <!-- `brown`, if selected, is the value that will be submitted to
         the server; user is displayed "Brown" as the choice -->
    <% @albums.each do |album| %>
      <% if album == @track.album %>
        <option value=<%=album.id%> selected = "selected"><%=album.name.capitalize%></option>
      <%else%>
        <option value="<%=album.id%>"><%=album.name.capitalize%></option>
      <%end%>
    <%end%>
  </select>
  <br>

  <label for="track_track_kind"> Track Type </label>
  <select name="track[track_kind]" id="track_track_kind" value=<%=@track.track_kind%>>
    <!-- `brown`, if selected, is the value that will be submitted to
         the server; user is displayed "Brown" as the choice -->
    <%types = ["bonus", "regular track"] %>
    <% types.each do |type| %>
      <% if type == @track.track_kind %>
        <option value=<%=type%> selected = "selected"><%=type.capitalize%></option>
      <%else%>
        <option value="<%=type%>"><%=type.capitalize%></option>
      <%end%>
    <%end%>
  </select>
  <br>

  <label for="track_lyrics"> Lyrics</label>
  <textarea name="track[lyrics]" id="track_lyrics" value = <%=@track.lyrics%>> </textarea>

  <input type="submit" value = '<%=submit_button%>' >
</form>

app/views/tracks/edit.html.erb
<h1> Update Track</h1>

<%=render "form", :action => :update_track %>

app/views/tracks/index.html.erb
<h1> Tracks </h1>

<table>
  <tr>
    <th>Name of Track</th>
    <th>Album</th>
    <th>Band</th>
  </tr>
  <% @tracks.each do |track|%>
    <tr>
      <td><%= link_to track.name , track_url(track)%> </td>
      <td><%= track.album %> </td>
      <td><%= track.band %> </td>
    </tr>
    <br>
  <% end%>
</table>
<% if admin_log_in? %>
  <p><%= button_to "Create new track", new_track_url %></p>
<%end%>

app/views/tracks/new.html.erb
<h1> Create new Track</h1>

<%=render "form", :action => :new_track %>

app/views/tracks/show.html.erb
<h1> <%= @track.name%> <h1>
<%if current_user.admin %>
  <%= button_to "Delete", track_url(@track), :method => "delete" %>
<% end%>
<h2> <%= link_to @track.album.name, album_url(@track.album) %> </h2>
<h2> <%= link_to @track.band.name, band_url(@track.band) %> </h2>

<p> type: <%= @track.track_kind%> </p>
<p> lyrics: <%= @track.lyrics%> </p>

<form action='<%= track_notes_url(@track) %>' method= "POST">
  <%= auth_token_html %>

  <label for="note_body_text">Note</label>
  <textarea name="note[body_text]" id="note_body_text">
  </textarea>
  <br>

  <input type="submit" value = 'Submit' >
</form>
<h2> Notes </h2>
<%= render @track.notes %>