config/routes.rb
Rails.application.routes.draw do
  root to: "bands#index"

  resources :users do
    get 'toggleboolean'
    collection do
      get 'activate'
    end
  end
  resource :session
  resources :bands do
    resources :albums, only: [:index, :new, :create]
  end

  resources :albums, except: [:index, :new, :create]

  resources :tracks do
    resources :notes
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :password_digest, :email, :session_token, presence: true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :email, :session_token, :activation_token, uniqueness: true
  before_validation :ensure_token
  before_validation :give_activation_token

  def self.create_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_token_password!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def password= (unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email_find, password_find)
    user = User.find_by_email(email_find)

    if user && user.is_password?(password_find)
      return user
    else
      return nil
    end

  end

  private

  def ensure_token
    self.session_token ||= User.create_session_token
  end

  def give_activation_token
    self.activation_token = SecureRandom::urlsafe_base64(16)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_admin!, only: :index

  def index
    @users = User.all

    render :index
  end

  def new
    @user = User.new

    render :new
  end

  def create
    user = User.new(user_params)

    if user.save!
      msg = UserMailer.welcome_email(user)
      msg.deliver!
      redirect_to new_session_url
      # log_in(user)
    else
      flash[:errors] = [user.errors.full_messages]
      redirect_to new_user_url
    end

  end

  def show
    @user = current_user
    render :show
  end

  def activate
    user = User.find_by_activation_token(params[:activation_token])

    if user && params[:activation_token]
      user.activated = true
      log_in(user)
    else
      flash.now[:errors] = ["Record not found."]
      redirect_to new_user_url
    end
  end

  def toggleboolean
    User.find(params[:user_change].to_i).toggle!(:admin)

    redirect_to users_url
  end


  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1> Users </h1>

<table>
  <tr>
    <th> Email </th>
    <th> Admin</th>
    <th> Toggle Admin status </th>
  </tr>
  <% @users.each do |user|%>
    <tr>
      <td><%=user.email%> </td>
      <td><%= user.admin %> </td>
      <td><%= button_to "Toggle Admin status", user_toggleboolean_url(user), params: {user_change: user.id}, method: "get" %> </td>
    </tr>
    <br>
  <% end%>
</table>
<% if admin_log_in? %>
  <p><%= button_to "Create new track", new_track_url %></p>
<%end%>

app/views/users/new.html.erb
<h1> Sign Up</h1>

<%=render "shared/newform", :user => @user, :action => :sign_up %>

<!-- <form action='<%= users_url %>' method= "post" >
  <%= auth_token_html%>
  <label for="user_user_name"> Username (email id) </label>
  <input type="text" id="user_user_name" name="user[user_name]">
  <br>
  <label for="user_password"> Password </label>
  <input type= "text" id="user_password" name= "user[password]">
  <input type="submit" value="Create User" >
</form> -->

app/views/users/show.html.erb
<h1> <%= @user.email%> <h1>