config/routes.rb
Rails.application.routes.draw do
  root to: "bands#index"

  resources :users do
    get 'toggleboolean'
    collection do
      get 'activate'
    end
  end
  resource :session
  resources :bands do
    resources :albums, only: [:index, :new, :create]
  end

  resources :albums, except: [:index, :new, :create]

  resources :tracks do
    resources :notes
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :name, :band_id, :album_kind, presence: true
  validates :album_kind, inclusion: {in: ["live", "studio"]}

  has_many :tracks, :dependent => :destroy
  belongs_to :band

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all

    render :index
  end

  def show
    @album = Album.find(params[:id])

    render :show
  end

  def new
    @album = Album.new
    @bands = Band.all
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save!
      flash[:notices] = [" Album Created"]
      redirect_to album_url(@album)
    else
      flash.now[:errors] = ["Album could not be saved."]
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    @bands = Bands.all
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      flash[:notices] = ["Album Updated"]
      redirect_to album_url(@album)
    else
      flash.now[:errors] = ["Album could not be updated."]
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])

    @album.destroy!

    redirect_to albums_url
  end

  private

  def album_params
    params.require(:album).permit(:name, :band_id, :album_kind)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<% if action == :new_album %>
  <% send_url = band_albums_url%>
  <% submit_button = "Create Album"%>
<%else%>
  <% send_url = edit_album_url%>
  <% submit_button = "Update Album" %>
<% end%>


<form action='<%= send_url %>' method= "POST">
  <%= auth_token_html %>

  <% if action == :update_album%>
    <input type="hidden" value="PATCH" name="_method" >
  <%end%>

  <label for="album_name">Name</label>
  <input type="text" name="album[name]" id="album_name" value="<%=@album.name%>">
  <br>

  <label for="album_band_id"> Band </label>
  <!-- dropdown -->
  <select name="album[band_id]" id="album_band_id" value=<%=@album.band_id%>>
    <!-- `brown`, if selected, is the value that will be submitted to
         the server; user is displayed "Brown" as the choice -->
    <% @bands.each do |band| %>
      <% if band.id == params["band_id"].to_i %>
        <option value="<%=band.id%>" selected = "selected"><%= band.name.capitalize%></option>
      <%else%>
        <option value="<%=band.id%>"><%=band.name.capitalize%></option>
      <%end%>
    <%end%>
  </select>
  <br>

  <label for="album_album_kind"> Band Type </label>
  <select name="album[album_kind]" id="album_album_kind" value=<%=@album.album_kind%>>
    <!-- `brown`, if selected, is the value that will be submitted to
         the server; user is displayed "Brown" as the choice -->
    <%types = ["live", "studio"] %>
    <% types.each do |type| %>
      <% if type == @album.album_kind %>
        <option value=<%=type%> selected = "selected"><%=type.capitalize%></option>
      <%else%>
        <option value="<%=type%>"><%=type.capitalize%></option>
      <%end%>
    <%end%>
  </select>
  <br>

  <input type="submit" value = '<%=submit_button%>' >
</form>

app/views/albums/edit.html.erb
<h1> Update Album</h1>

<%=render "form", :action => :update_album %>

app/views/albums/new.html.erb
<h1> Create new Album</h1>

<%=render "form", :action => :new_album %>

app/views/albums/show.html.erb
<h1> <%= @album.name%> <h1>
<% if admin_log_in? %>
    <%= button_to "Delete", album_url(@album), :method => "delete" %>
  <% end%>

<h2> <%= link_to @album.band.name, band_url(@album.band) %> </h2>
<p> <%= @album.album_kind%> </p>


<h2>Tracks<h2>
    <ul>
    <% @album.tracks.each do |track| %>
       <li><%= link_to track.name, track_url(track) %> </li>
    <% end %>
    </ul>
</ol>