config/routes.rb
Rails.application.routes.draw do
  root to: "bands#index"

  resources :users do
    get 'toggleboolean'
    collection do
      get 'activate'
    end
  end
  resource :session
  resources :bands do
    resources :albums, only: [:index, :new, :create]
  end

  resources :albums, except: [:index, :new, :create]

  resources :tracks do
    resources :notes
  end

end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums, :dependent => :destroy

  has_many :tracks, through: :albums, source: :tracks
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :ensure_admin!, only: [:create, :update, :destroy]



  def index
    @bands = Band.all

    render :index
  end

  def show
    @band = Band.find(params[:id])
    @albums = @band.albums
    @tracks = @band.tracks
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      flash[:notices] = [" Band Created"]
      redirect_to band_url(@band)
    else
      flash.now[:errors] = ["Band could not be saved."]
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      flash[:notices] = ["Band Updated"]
      redirect_to band_url(@band)
    else
      flash.now[:errors] = ["Band could not be updated."]
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])

    @band.destroy!

    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end


end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<% if action == :new_band %>
  <% send_url = bands_url%>
  <% submit_button = "Create Band"%>
<%else%>
  <% send_url = band_url%>
  <% submit_button = "Update Band" %>
<% end%>


<form action='<%= send_url %>' method= "POST">
  <%= auth_token_html %>

  <% if action == :update_band%>
    <input type="hidden" value="PATCH" name="_method" >
  <%end%>

  <label for="band_name">Name</label>
  <input type="text" name="band[name]" id="band_name" value="<%=@band.name%>">
  <br>

  <input type="submit" value = '<%=submit_button%>' >
</form>

app/views/bands/edit.html.erb
<h1> Update Band</h1>

<%=render "form", :action => :update_band %>

app/views/bands/index.html.erb
<h1> Bands </h1>

<table>
  <tr>
    <th>Band</th>
    <!-- <th>Album</th>
    <th>Band</th> -->
  </tr>
  <% @bands.each do |band|%>
    <tr>
      <td><%= link_to band.name , band_url(band)%> </td>

    </tr>
    <br>
  <% end%>
</table>

<% if admin_log_in? %>
  <p><%= button_to "Create new band", new_band_url %></p>
<% end%>

app/views/bands/new.html.erb
<h1> Create new Band</h1>

<%=render "form", :action => :new_band %>

app/views/bands/show.html.erb
<h1> <%= @band.name%> <h1>
<% if admin_log_in? %>
  <%= button_to "Delete", band_url(@band), :method => "delete" %>
<% end%>

<h2>Albums<h2>
  <ol>
  <% @albums.each do |album|%>
    <li> <%= link_to album.name, album_url(album) %> </li>
    <ul>
    <% album.tracks.each do |track| %>
       <li><%= link_to track.name, track_url(track) %> </li>
    <% end %>
    </ul>
  <% end%>
</ol>

<% if admin_log_in? %>
  <%=button_to "Add Album", new_band_album_url(@band), :method => "get" %>
<% end%>